/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as AdminNewsIndexRouteImport } from './routes/admin/news/index'
import { Route as AdminNewsNewRouteImport } from './routes/admin/news/new'
import { Route as AdminNewsIdEditRouteImport } from './routes/admin/news/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/admin/news/',
  path: '/admin/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/admin/news/new',
  path: '/admin/news/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsIdEditRoute = AdminNewsIdEditRouteImport.update({
  id: '/admin/news/$id/edit',
  path: '/admin/news/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/settings'
    | '/news/$slug'
    | '/admin/'
    | '/admin/news/new'
    | '/admin/news/'
    | '/admin/news/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/settings'
    | '/news/$slug'
    | '/admin'
    | '/admin/news/new'
    | '/admin/news'
    | '/admin/news/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/settings'
    | '/news/$slug'
    | '/admin/'
    | '/admin/news/new'
    | '/admin/news/'
    | '/admin/news/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  NewsSlugRoute: typeof NewsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminNewsIdEditRoute: typeof AdminNewsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/admin/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/admin/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/$id/edit': {
      id: '/admin/news/$id/edit'
      path: '/admin/news/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof AdminNewsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  NewsSlugRoute: NewsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminNewsNewRoute: AdminNewsNewRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminNewsIdEditRoute: AdminNewsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
